# Data Science in Psychology & Neuroscience (DSPN): 

## Lecture 5. Conditionals

### Date: September 1, 2020

### To-Dos From Last Class:

* Submit Assignment #1: <a href="https://www.dropbox.com/request/VNNoOUDkK7Vpw4N6l1wv">Oscillator</a> (before 9/1, 23:00 MDT)

### Today:

* if
* elif
* else
* Multiple criteria (Boolean operators)
* Conditionals+iterations

### Homework

* Read short primer on the "integrate and fire" neuron
* Download Assignment #2 starter kit from <a href="https://github.com/hogeveen-lab/DSPN_Fall2020_git">github</a>


# Conditionals: IF

* __IF__ statements check for a condition, and only execute a set of code if the condition is _True_.
    * What type of logic is this?
* Boolean logic: 
    * Based on Boolean algebra, foundation of digital tech and all programming languages
    * Boolean algebra evaluates the truth value of a given statement
* Can use __IF__ in isolation when you want a _single_ output solution.
    * If true, do this
    * Otherwise, do nothing

In [13]:
condition = True

if condition:
    print('This code executes if the condition evaluates as True.')

This code executes if the condition evaluates as True.


In [12]:
participants = 64
trials = 240

df_length = 15360

if (participants*trials) == df_length:
    print('All trials present in df') # RUN BOTH AS EQUALS AND DOES NOT EQUAL

All trials present in df


In [11]:
favorite_tv = ['the_wire','breaking_bad','community']
wifes_favorite = 'community'

if wifes_favorite in favorite_tv:
    print('the marriage will last!')

the marriage will last!


# Conditionals: ELSE

* __ELSE__ statements always appear after an __IF__, and explicitly define an alternative action plan. 
* A simple __IF then ELSE__ sequence is useful if you are looking for a solution with _two_ possible outputs.

In [10]:
condition = False

if condition:
    print('This code executes if the condition evaluates as True.')
else:
    print('This code executes if the condition evaluates as False.')
    

This code executes if the condition evaluates as False.


In [9]:
participants = 64
trials = 240
df_length = 15320

if (participants*trials) == df_length:
    print('all trials present in df')
else:
    print('you are missing some trials')
    

you are missing some trials


In [8]:
favorite_tv = ['the_wire','breaking_bad','community']
wifes_favorite = 'the_office'

if wifes_favorite in favorite_tv:
    print('the marriage will last!')
else:
    print('the marriage is doomed!')

the marriage is doomed!


# Conditionals: ELIF

* When the solution requires >2 possible outputs, any number of __ELIF__ (aka __ELSEIF__ in MATLAB, __ELSE IF__ in R) statements can be chained together _after_ an __IF__.
* A subsequent __ELSE__ is not required, but if you leave it out then the code will return nothing if both __IF__ and __ELIF__ are not _True_.
* __ELIF__ after __ELSE__ does not make sense.


In [7]:
favorite_tv = ['the_wire','breaking_bad','community']
pretty_enjoyable = ['the_office','daily_show','top_chef']
wifes_favorite = 'the_office'

if wifes_favorite in favorite_tv:
    print('the marriage will last!')
elif wifes_favorite in pretty_enjoyable:
    print('the marriage has a chance!')
else:
    print('the marriage is doomed!')

the marriage has a chance!


In [6]:
participants = 64
trials = 240
df_length = 15420

if (participants*trials) == df_length:
    print('all trials present in df')
elif (participants*trials) > df_length:
    print('you are missing some trials')
elif (participants*trials) < df_length:
    print('you have repeated trials')

you have repeated trials


# Multiple criteria to be satisfied (add Boolean operators)

* When using these, think how you use Google search 
    * "Portobello burger" AND "soy sauce"
    * "Portobello burger" OR "seitan burger"
    * "Portoboello burger" NOT "balsamic vinegar"
* __AND__ can be used when multiple criteria must be satisfied to return a given output.

In [5]:
stim_a = 1
stim_b = 2
trial_num = 2

response = 1

if response == stim_a and trial_num < 3:
    print('A early')
elif response == stim_b and trial_num < 3:
    print('B early')
else:
    print('late trial')

A early


* __OR__ can be used when any of the listed criteria can be satisfied to return a given output.

In [3]:
no_resp = 999
wrong_resp = 0

curr_trial = 999

if curr_trial == no_resp or curr_trial == wrong_resp:
    print('remove trial from analysis')
else:
    print('keep trial in analysis')

remove trial from analysis


# Conditional expressions within a FOR loop

* Sometimes, you might want to iterate over something and make decisions as you go

__E.g.: create two random 10-number integer arrays from 0-100. For each pair of integers, if they are both over or under 50 return the number 1, otherwise return 0__

In [1]:
for i in range(10):
    if (i == 2 or i==6 or i ==9):
        continue
    print(i,end=' ')
print("\n")

0 1 3 4 5 7 8 



In [2]:
# Preamble -- part of the code we can mess with.
# Packages
import numpy as np

array_1 = np.random.randint(0,100,size=10)
array_2 = np.random.randint(0,100,size=10)
result_array = np.array([])
threshold=50

# Iterating over size=N integers and
for i in range(0,len(array_1)):
    # If both even then...
    if array_1[i] > threshold and array_2[i] > threshold:
        # add match to our new array
        result=1
        result_array = np.append(result_array, result)
    # If both odd then...
    elif array_1[i] < threshold and array_2[i] < threshold:
        # add match to our new array
        result=1
        result_array = np.append(result_array, result)
    # otherwise...
    else:
        # add nonmatch to our new array
        result=0
        result_array = np.append(result_array, result)

# Checking our work
print(array_1)
print(array_2)
print(result_array.astype(int))

[74 27  8 95  6 46 61 50 75 76]
[ 7 88  0 84 71 21 80  7  8 69]
[0 0 1 1 0 1 1 0 0 1]
